# NumPy Indexing and Selection
In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python list:

In [4]:
# Get a value at an index
arr[8]

8

In [5]:
# Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6] # same as arr[0:6]

array([0, 1, 2, 3, 4, 5])

## Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [8]:
# Setting a value with index range (Broadcasting)
arr[0:5] = 100

# Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:6]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:] = 99

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!!!

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's view of the original array! This avoid memory problems!

In [18]:
# To get a copy, need to be explicit
arr_copy = arr.copy()

In [19]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy[:] = 5

In [21]:
arr_copy

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

"arr" not change !