# NumPy Indexing and Selection

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [1]:
import numpy as np

In [3]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [4]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [10]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [7]:
# Format is arr_2d[row][col] or arr_2d[row,col]
arr_2d[1,0]

20

In [8]:
arr_2d[1][0]

20

In [11]:
# 2D array slicing
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [12]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [14]:
arr_2d[:2][1:] #ไม่เหมือนกันกับ arr_2d[:2,1:] นะ

array([[20, 25, 30]])