# Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built-in Methods

## Arange
Return evenly spaced values within a given interval.

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## zeros and ones
Generate arrays of zeros or ones

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,3)) # (row, column)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3,4)) # (row, column)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linspace
Return evenly spaced numbers over a specified interval.

In [15]:
np.linspace(0,5,10) # (start , stop , number)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.linspace(0,5) # (start , stop , default = 50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

## eye
Creates an identity matrix (I)

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random
Numpy also has lots of ways to create random number arrays:

## rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)

In [18]:
np.random.rand(2)

array([0.07717233, 0.01878966])

In [20]:
np.random.rand(2,3) # row,column

array([[0.72624862, 0.36450406, 0.92809515],
       [0.45828275, 0.25267194, 0.03342137]])

## randn
Return a sample ( or samples ) from the "standard normal" distribution. Unlike rand which is uniform

In [21]:
np.random.randn(2)

array([-0.21427629, -1.32935143])

In [22]:
np.random.randn(4,5) # row,column

array([[-0.68701687,  0.9496871 , -0.16690169,  0.5465094 , -2.02664367],
       [-0.32841476,  0.04639052, -0.2996311 , -0.05293459, -0.41889749],
       [-0.34662585, -0.51130227, -0.47019955,  1.08133066, -1.17021249],
       [ 1.09409927, -0.21954934,  1.21019933, -0.5202072 , -0.49578877]])

## randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [23]:
np.random.randint(1,100) # low possible , high possible

92

In [25]:
np.random.randint(1,100, size = (2,3))

array([[64, 28, 22],
       [ 9, 13, 57]])

# Array Attributes and Methods
Let's discuss some useful attributes and methods or an array:

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([27, 31, 43, 22, 46, 46,  7,  2, 33, 39])

## Reshape
Returns an array containing the same data with a new shape.

In [29]:
arr.reshape(5,5) # ROW, COLUMN

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## max , min , argmax , argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax.

In [30]:
ranarr

array([27, 31, 43, 22, 46, 46,  7,  2, 33, 39])

In [31]:
ranarr.max()

46

In [32]:
ranarr.min()

2

In [33]:
ranarr.argmax() # return index location of max value

4

In [34]:
ranarr.argmin() # return index location of min value

7

## Shape
Shape is an attribute that arrays have (not a method)!! :

In [36]:
# Vector
arr.shape

(25,)

In [37]:
arr = arr.reshape(5,5)

In [38]:
arr.shape

(5, 5)

In [39]:
arr.dtype # check element type

dtype('int32')

In [40]:
arr.reshape(25,1) # row,column

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

# Trick to abbreviate 

In [41]:
from numpy.random import randint

In [44]:
randint(5,10)

7